name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v4
    - name: Login to Scaleway Container Registry
      uses: docker/login-action@v3
      with:
        username: nologin
        password: ${{ secrets.SCALEWAY_API_KEY }}
        registry: ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}
    - name: Build the Docker image
      run: docker build . -t ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/bienvenu
    - name: Push the Docker Image
      run: docker push ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/bienvenu


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # SSH into the Scaleway server
      - name: Deploy to Scaleway server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SCALEWAY_SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          # Run commands on the remote server
          script: |
           
            # Stop the current container if running
            docker stop bienvenu || true
            docker rm bienvenu || true
           
            # Pull the latest Docker image from the registry
            docker pull ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/bienvenu:latest

            # Run the new container
            docker run -d --name eugeniotest -p 8023:8023 ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/bienvenu:latest
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag zach27/atut-bootcamp:v1
    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #     ecr: auto
    #     logout: true
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    # - name: Extract metadata (labels, tags, etc.) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v5
    #   with:
    #     images: zach27/atut-bootcamp:v0
    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v5
    #   with:
    #       context: .
    #       file: ./Dockerfile
    #       push: true
    #       tags: zach27/atut-bootcamp:v1
    #       labels: ${{ steps.meta.outputs.labels }}

    
